name: Run unit tests

on:
  push:
    branches: [ "main" ]
    paths: [ "question-service/**", "matching-service/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "question-service/**", "matching-service/**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['6.0']

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './question-service/package-lock.json'

    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: ${{ matrix.redis-version }}

    - run: npm ci
      working-directory: ./question-service
    - run: npm test
      working-directory: ./question-service
